### PR TITLE
Implement DDPM Scheduler

### PR DESCRIPTION
**Pull request by mspronesti**
Hello,
this PR aims at integrating the [DDPMScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py) into this beautiful rust implementation of the diffusers API. 

I made it a draft because, despite the implementation seems (to me) to be sound, using the `stable_diffusion` pipeline as it is with this new scheduler, the final image is nothing but noise. I'm still working on it, but I wanted to show this "work-in-progress" result in case anybody wanted to point out anything / help .

### CODE REVIEW

**Comment by LaurentMazare** [comment]
Looks pretty interesting! What I usually did when getting noise back for the generated image was lining things up between the python and rust implementation, they are close enough so that it's easy to fix the seed and get almost identical numbers on both sides (and for the scheduler I guess there is even a lot less randomness involved in the process).

**Comment by mspronesti** [comment]
Hello @LaurentMazare,
thanks for the feedback. This implementation is in fact sound: I tried again with the official python implementation, specifically this [notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/diffusers_intro.ipynb), and I played around with the number of inference steps. Nothing below 1000 produced a "meaningful" image (I was "testing" the rust version with 30, 100, 200). 

With 1000 steps, I'm getting back a meaningful result with the code of this PR. I'm marking it as "Ready for review" :)

**Review by LaurentMazare — APPROVED** [review]

**Comment by LaurentMazare** [comment]
Merged, thanks for the PR!

**Comment by JohnAlcatraz** [comment]
Can someone maybe explain what this DDPM schedulers is, what makes it cool, when it should be used? If it needs 1000 steps for a proper result, it sounds extremely slow?

**Comment by mspronesti** [comment]
@JohnAlcatraz Sorry, I must have missed your comment. The scheduler contained a bug when used with less  inference steps than training timesteps (both the python and rust version). Should be fixed now.

**Pull request merged**
